INSERT INTO BURGERS(BURGER_NAME) VALUES("Chillie cheese burger");
INSERT INTO BURGERS(BURGER_NAME) VALUES("Big Mac burger");
INSERT INTO BURGERS(BURGER_NAME) VALUES("Barbeque Chicken burger");
INSERT INTO BURGERS(BURGER_NAME,DEVOURED) VALUES("Beyond meat burger",TRUE);
